export type ContentImage = {
  src: string;
  alt: string;
  width: number;
  height: number;
  caption?: string;
  /**
   * CSS object-position for fitting a photograph into the cards' 3:2 frame, when the centre is
   * the wrong place to crop — "50% 30%" keeps the upper part. Defaults to the centre.
   */
  focus?: string;
  sourceFile?: string;
  pageOrSlide?: number;
  attribution?: {
    creator: string;
    sourceUrl: string;
    license: string;
    /** Absent for public-domain works, which have no licence deed to link to. */
    licenseUrl?: string;
  };
};

/**
 * Real photos/figures that support a specific content unit,
 * keyed by content_unit id. Rendered inside that specific ContentUnit card
 * (unlike topicDiagrams in diagrams.ts, which is one figure per topic).
 * Course-source images record their source file and page. Openly licensed
 * supporting photos must record creator, source URL, and licence attribution.
 */
export const contentImages: Record<string, ContentImage> = {
  "53ea1015-3e72-4d7f-867e-77f2ca172e82": {
    src: "/content-images/ch4-atoll-hd.webp",
    alt: "Atafu atoll photographed from orbit: a narrow ring of sand and palm islets enclosing a pale turquoise lagoon, set in deep blue ocean",
    width: 1600,
    height: 1089,
    caption: "Atafu atoll, Tokelau, seen from the International Space Station",
    attribution: {
      creator: "Earth Science and Remote Sensing Unit, NASA Johnson Space Center",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Atafu_atoll,_Tokelau_(ISS014-E-19881).jpg",
      license: "Public domain",
    },
  },
  "971fd72e-38c8-473b-96ef-b1c7c8204d53": {
    src: "/content-images/ch4-island-hd.webp",
    alt: "A large island seen from the air, its ridged green interior fringed by pale shallows, with smaller islands scattered around it",
    width: 1600,
    height: 1067,
    caption: "Jindo, South Korea, from the air",
    attribution: {
      creator: "Andrzej Otrębski",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Jindo_aerial.jpg",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  "ae492e89-3265-45c4-8d4d-838761569a4d": {
    src: "/content-images/ch4-cays-hd.webp",
    alt: "A low coral cay on the Great Barrier Reef: a bare sandbank barely above turquoise shallows, with a boat drawn up on it and visitors on the sand",
    width: 1600,
    height: 1064,
    caption: "Michaelmas Cay, Great Barrier Reef",
    attribution: {
      creator: "Ron Knight",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Michaelmas_Cay,_Great_Barrier_Reef_(8601956159).jpg",
      license: "CC BY 2.0",
      licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    },
  },
  "8bb2eaca-0afd-45c8-8ecb-d9a3d0209a99": {
    src: "/content-images/ch4-peninsula-hd.webp",
    alt: "A grassy headland running out into the sea and widening into a flat-topped promontory, water on both sides",
    width: 1600,
    height: 1068,
    caption: "A peninsula reaching out into the sea",
    attribution: {
      creator: "Stefan Kunze",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Green_peninsula_(Unsplash).jpg",
      license: "CC0",
      licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    },
  },
  "ab312ce7-5f79-4740-a227-ac4c0e3bc6ef": {
    src: "/content-images/ch3-p3-latitude-globe.jpg",
    alt: "Labelled globe diagram showing the North Pole, Arctic Circle, Tropic of Cancer, Equator, Tropic of Capricorn, Antarctic Circle, and South Pole",
    width: 550,
    height: 384,
    caption: "Latitude — chapter-3.pdf, p3",
    sourceFile: "chapter-3.pdf",
    pageOrSlide: 3,
  },
  "04c61a82-dd00-40f8-a954-3bce4182d47c": {
    src: "/content-images/ch3-p4-longitude-globe.jpg",
    alt: "Globe diagram showing longitude meridian lines converging at the poles, labelled with degrees east and west and the Prime Meridian",
    width: 320,
    height: 312,
    caption: "Longitude — chapter-3.pdf, p4",
    sourceFile: "chapter-3.pdf",
    pageOrSlide: 4,
  },
  "2aa381ff-f92f-4fcd-8dec-43674a4f0903": {
    src: "/content-images/ch3-greenwich-clock-hd.webp",
    alt: "The Shepherd Gate clock at the Royal Observatory, Greenwich: a 24-hour dial set into a brick wall, its single hand pointing to the hour, lettered Shepherd Patentee and Galvano-Magnetic Clock",
    width: 1600,
    height: 1424,
    caption: "The Shepherd Gate clock at the Royal Observatory, Greenwich — the public face of Greenwich Mean Time",
    attribution: {
      creator: "Alvesgaspar",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Greenwich_clock_1-manipulated.jpg",
      license: "CC BY-SA 3.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    },
  },
  "6fd79ae0-63ed-4a1c-972d-091ac7e688cb": {
    src: "/content-images/ch3-prime-meridian-hd.webp",
    alt: "Looking down at two feet standing either side of the brass Prime Meridian strip at the Royal Observatory, Greenwich, with city longitudes engraved in the paving on both sides — New York, Madrid and Lisbon to the west, Rome, Istanbul and Beijing to the east",
    width: 1600,
    height: 900,
    caption: "One foot in each hemisphere at the Royal Observatory, Greenwich. The plaque engraves cities either side of the line — the ones in frame here are New York, Madrid and Lisbon to the west, Rome, Istanbul and Beijing to the east",
    attribution: {
      creator: "LondonHistoryatHome",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Feet_on_prime_meridian_greenwich_observatory.jpg",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  "a6943945-1c7c-4ea8-a5b2-2552428119bc": {
    src: "/content-images/ch3-p10-time-zone-map.jpg",
    alt: "World time zone map with a row of clock faces from noon to midnight, colour-banded time zones, the Greenwich Meridian, and the International Date Line marked between Sunday and Monday",
    width: 839,
    height: 495,
    caption: "World time zones and the International Date Line — chapter-3.pdf, p10",
    sourceFile: "chapter-3.pdf",
    pageOrSlide: 10,
  },
  "3868dc9c-a755-441c-9920-c385a6b86634": {
    src: "/content-images/ch1-p13-plaza-de-espana.jpg",
    alt: "Plaza de España, Seville — a semicircular brick-and-ceramic palace with towers, a canal, and an ornate tiled bridge",
    width: 900,
    height: 600,
    caption: "Plaza de España, Seville — chapter-1.pdf, p13",
    sourceFile: "chapter-1-candidate-a.pdf",
    pageOrSlide: 13,
  },
  "25f51ac3-0193-4428-a2a7-a1031cfdef6e": {
    src: "/content-images/ch1-p14-kl-skyline.jpg",
    alt: "Kuala Lumpur skyline at night, with the illuminated Petronas Twin Towers at centre",
    width: 900,
    height: 521,
    caption: "Kuala Lumpur skyline — chapter-1.pdf, p14",
    sourceFile: "chapter-1-candidate-a.pdf",
    pageOrSlide: 14,
  },
  "a92b84df-02e5-4635-872c-507863427545": {
    src: "/content-images/ch1-p15-travel-route.jpg",
    alt: "An empty straight two-lane road running to a vanishing point between golden crop fields",
    width: 960,
    height: 659,
    caption: "Travel routes — chapter-1.pdf, p15",
    sourceFile: "chapter-1-candidate-a.pdf",
    pageOrSlide: 15,
  },
  "571f3d66-5474-4ad0-8479-56c06e609134": {
    src: "/content-images/ch1-halal-tourism-hd.webp",
    alt: "The Sultan Omar Ali Saifuddien Mosque in Bandar Seri Begawan: a white mosque with a gold dome and tall minarets under a blue sky",
    width: 1600,
    height: 1067,
    caption: "The Sultan Omar Ali Saifuddien Mosque, Bandar Seri Begawan, Brunei",
    attribution: {
      creator: "Jorge Láscar from Melbourne, Australia",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Sultan_Omar_Ali_Saifuddien_Mosque_(17971529663).jpg",
      license: "CC BY 2.0",
      licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    },
  },
  "11b8ee9b-269a-49f1-b1c1-571951ce1e81": {
    src: "/content-images/ch2-midlat-mediterranean-hd.webp",
    alt: "Tuscan hillside in summer: rows of vines and grey-green olive groves on dry slopes, with dark upright cypresses and a hill village in the haze beyond",
    width: 1600,
    height: 1067,
    caption: "Olive groves, vines and cypresses in Chianti, Tuscany",
    attribution: {
      creator: "bongo vongo",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Olive_groves,_grape_vines_and_cypresses_in_Chiantishire_(4054460424).jpg",
      license: "CC BY-SA 2.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    },
  },
  "fc62a899-7a5c-4f04-b075-372d5c735849": {
    src: "/content-images/ch2-midlat-marine-west-coast-hd.webp",
    alt: "Temperate rainforest floor in the Hoh valley, where fallen logs, standing trunks and low branches are all thickly covered in bright green moss and ferns",
    width: 1600,
    height: 1029,
    caption: "Moss-covered temperate rainforest, Hoh valley, Olympic National Park, Washington",
    attribution: {
      creator: "Olympic National Park (NPS)",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Hoh_Rainforest,_mossy_log_tree_NPS_Photo_(16680304244).jpg",
      license: "Public domain",
    },
  },
  "856b9788-22cc-4435-9231-654443412c72": {
    src: "/content-images/ch2-midlat-humid-continental-hd.webp",
    alt: "A frozen reservoir under deep snow, ringed by snow-laden conifers, with snow-capped mountains on the far shore under a clear winter sky",
    width: 1600,
    height: 1200,
    caption: "Chittenden Reservoir frozen over, Green Mountain National Forest, Vermont",
    attribution: {
      creator: "USDA Forest Service",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Green_Mountain_National_Forest_(20241222-FS-GM-BME-ChittendenReservoir-001).jpg",
      license: "Public domain",
    },
  },
  "0e07433e-b0f7-442f-a49a-0e2515a3f401": {
    src: "/content-images/ch2-p13-climate-zones-by-latitude.jpg",
    alt: "World map banded into five horizontal climate zones — Arctic, Mid-latitudes, Tropics, Mid-latitudes, Antarctic — each labelled with its season count",
    width: 700,
    height: 421,
    caption: "Climate zones by latitude — chapter-2.pdf, p13",
    sourceFile: "chapter-2.pdf",
    pageOrSlide: 13,
  },
  "0cf701f8-8fde-407e-ae4f-d532dab52975": {
    src: "/content-images/ch2-tropical-rainforest-hd.webp",
    alt: "Dense, layered primary tropical rainforest covering the limestone hills of Khao Sok in southern Thailand",
    width: 1600,
    height: 1067,
    caption: "Primary tropical rainforest in Khao Sok, southern Thailand",
    attribution: {
      creator: "Vyacheslav Argenberg",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Khao_Sok_primary_tropical_rainforest,_southern_Thailand.jpg",
      license: "CC BY 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    },
  },
  "82c13fdc-c0c5-46d7-9320-d2cf89f273fc": {
    src: "/content-images/ch2-summer-monsoon-hd.webp",
    alt: "Heavy summer monsoon clouds and rain over a waterlogged green landscape with mountains in the distance",
    width: 1600,
    height: 898,
    caption: "Moist summer-monsoon conditions",
    attribution: {
      creator: "lensnmatter",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Monsoon_(36877269620).jpg",
      license: "CC BY 2.0",
      licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    },
  },
  "c31bc5c9-c35d-4686-af03-166c4ff45227": {
    src: "/content-images/ch2-winter-monsoon-hd.webp",
    alt: "Northern Thai valley in the dry season: the Nan River reduced to a narrow stream across a wide gravel bed, with harvested paddy terraces and haze over the hills",
    width: 1600,
    height: 1000,
    caption: "Dry-season conditions in Nan Province, Thailand, photographed in December — the Nan River near its source, barely more than a stream",
    attribution: {
      creator: "Takeaway",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:2013_Chaloem_Phra_Kiat_District_Nan.jpg",
      license: "CC BY-SA 3.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    },
  },
  "5991f254-816b-4035-ab43-1f911804a967": {
    src: "/content-images/ch2-tropical-savanna-hd.webp",
    alt: "Open Serengeti grassland dotted with flat-topped acacia trees beneath a broad blue sky",
    width: 1600,
    height: 922,
    caption: "Tropical savanna in Serengeti National Park, Tanzania",
    attribution: {
      creator: "Bjørn Christian Tørrissen",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Serengeti-Landscape-2012.JPG",
      license: "CC BY-SA 3.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    },
  },
  "27a0eeb9-953f-4ac7-9e86-55d9e8789006": {
    src: "/content-images/ch2-dry-oasis-hd.webp",
    alt: "Timimoun oasis in the Algerian desert, with water and dense date palms surrounded by arid terrain",
    width: 1280,
    height: 960,
    caption: "Oasis at Timimoun in the Algerian desert",
    attribution: {
      creator: "Taguelmoust",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Oasis_timimoun.png",
      license: "CC BY-SA 3.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    },
  },
  "3351e87e-e9ef-44f4-bb9e-25d1b334cdde": {
    src: "/content-images/ch2-dry-steppe-hd.webp",
    alt: "Treeless Eurasian steppe in Inner Mongolia, with extensive grassland beneath a wide sky",
    width: 1600,
    height: 1200,
    caption: "Eurasian steppe grassland in Inner Mongolia",
    attribution: {
      creator: "Shizhao",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Grasslands-menggu.JPG",
      license: "CC BY-SA 3.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    },
  },
  "f1012de4-075c-4ab5-a441-1cfb3a871732": {
    src: "/content-images/ch2-midlat-deciduous-forest-hd.webp",
    alt: "Steep valley sides blanketed in broad-leaved forest turning orange, red and gold in autumn, with a stream in the shaded valley floor",
    width: 1600,
    height: 1067,
    caption: "Deciduous forest in autumn colour, Jogakura Valley, Hakkoda Mountains, Japan",
    attribution: {
      creator: "lumoplank",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Hakkoda_Mountains,_Part_III-_Jogakura_Valley_-_Hakkoda6899.jpg",
      license: "CC0",
      licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    },
  },
  "597fd168-ea69-4012-be79-c730070b952f": {
    src: "/content-images/ch2-midlat-evergreen-forest-hd.webp",
    alt: "Stand of tall pines with straight bare trunks and needled crowns high above, over a green ground cover of bilberry and lichen",
    width: 1600,
    height: 1200,
    caption: "Coniferous forest near the Svartalven river, Sweden",
    attribution: {
      creator: "Leonhard Lenz",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Coniferous_forest_in_Sweden_near_the_Svart%C3%A4lven_river_01.jpg",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  "6e94cafe-6b33-451f-9f77-a41ce89f09e5": {
    src: "/content-images/ch2-highlat-subarctic-hd.webp",
    alt: "Dense dark coniferous taiga covering hills around a small lake, with low scrub in the foreground and no broad-leaved trees",
    width: 1600,
    height: 1067,
    caption: "Siberian taiga, Ergaki Range, Krasnoyarsk Krai, Russia",
    attribution: {
      creator: "Vyacheslav Argenberg",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Ergaki,_Taiga_in_Siberia,_Coniferous_forest,_Sayan_Mountains,_Siberia,_Russia.jpg",
      license: "CC BY 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    },
  },
  "e6f73628-6399-476a-aa9e-75fd75b98944": {
    src: "/content-images/ch2-highlat-tundra-hd.webp",
    alt: "Treeless Arctic tundra in autumn: scarlet and gold low shrubs, mosses and lichen over rock, with only a few stunted birches and a bare ridge behind",
    width: 1600,
    height: 1067,
    caption: "Arctic tundra in autumn colour, Kola Peninsula, Russia",
    attribution: {
      creator: "Artem Abdukakharov",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Arctic_tundra_in_autumn_colors_near_lake_Lovozero_in_Murmansk_Oblast,_Russia.jpg",
      license: "CC BY 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    },
  },
  "7327549a-dc74-470d-9274-80fdfc13506b": {
    src: "/content-images/ch2-highlat-ice-cap-hd.webp",
    alt: "The Greenland ice sheet from an aircraft: an unbroken white surface of ice stretching to the horizon, breaking into crevasses where it meets bare coastal rock",
    width: 1600,
    height: 1089,
    caption: "The Greenland ice sheet, seen from the air over the east coast",
    attribution: {
      creator: "Hannes Grobe",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Greenland-ice_sheet_hg.jpg",
      license: "CC BY-SA 2.5",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/2.5/",
    },
  },
  "7bc6947d-0d4c-441a-817c-77284ad40069": {
    src: "/content-images/ch2-highland-treeline-hd.webp",
    alt: "Mount Hood above its tree line: conifers grow in the foreground and then stop, leaving bare rock, scree and snowfields on the peak above",
    width: 1600,
    height: 1217,
    caption: "The tree line on Mount Hood, Oregon: forest below, bare rock and snow above",
    attribution: {
      creator: "inkknife_2000",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Mount_Hood_Tree_Line,_OR_8-13_(16171629489).jpg",
      license: "CC BY-SA 2.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    },
  },
  "15c93c2f-a904-4d1b-bec5-6275c231cf68": {
    src: "/content-images/ch4-nature-tourism-hd.webp",
    alt: "Visitors at the Navajo Point viewpoint looking out over the Grand Canyon, its red and orange walls running to the horizon under a blue sky",
    width: 1600,
    height: 1067,
    caption: "Visitors at Navajo Point, Grand Canyon National Park — enjoying an undisturbed natural environment",
    attribution: {
      creator: "Marek Ślusarczyk (Tupungato) Photo portfolio",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:10_Grand_Canyon_Navajo_Point_viewpoint_terrace,_Grand_Canyon_National_Park,_USA_-_American_nature.jpg",
      license: "CC BY 3.0",
      licenseUrl: "https://creativecommons.org/licenses/by/3.0/",
    },
  },
  "0da062ff-1e92-42bb-bfd1-e5617f5764bf": {
    src: "/content-images/ch4-p3-hand-mountain.jpg",
    alt: "A first-person view of an open hand and forearm outstretched toward a forested mountain ridge",
    width: 1800,
    height: 1200,
    caption: "Recognizing a landscape as a tourism resource — chapter-4.pdf, p3",
    sourceFile: "chapter-4.pdf",
    pageOrSlide: 3,
  },
  "2d67b8a0-9232-4918-9b10-9570fa80f03e": {
    src: "/content-images/ch4-p9-hiker-lake.jpg",
    alt: "A hiker with a large backpack standing on a lakeside boardwalk, facing a still green-blue alpine lake ringed by dense conifer forest",
    width: 1728,
    height: 1152,
    caption: "Natural landscape — chapter-4.pdf, p9",
    sourceFile: "chapter-4.pdf",
    pageOrSlide: 9,
  },
  "a46327c7-105d-4034-b217-620132142f42": {
    src: "/content-images/ch4-p10-waterfall.jpg",
    alt: "A waterfall dropping through dark wet rock into a plunge pool surrounded by moss and ferns",
    width: 1160,
    height: 870,
    caption: "Waterfall — chapter-4.pdf, p10",
    sourceFile: "chapter-4.pdf",
    pageOrSlide: 10,
  },
  "d0887588-5176-4ed4-bc95-b7658bc61ac1": {
    src: "/content-images/ch4-p14-kinabalu-signboard.png",
    alt: "Three climbers celebrating at the Low's Peak summit signboard on Mount Kinabalu, reading TAMAN KINABALU and the summit height",
    caption: "Climbers at the Low's Peak summit board — chapter-4.pdf, p14",
    width: 505,
    height: 375,
    sourceFile: "chapter-4.pdf",
    pageOrSlide: 14,
  },
  "e55a19ac-f045-454e-9a37-786b141b5ddd": {
    src: "/content-images/ch4-plateau-hd.webp",
    alt: "Flat-topped mesas standing above a dry plain in Namibia, with a mountain rising behind them through the haze",
    width: 1600,
    height: 1058,
    caption: "Flat-topped plateaus above the plain, Namibia",
    attribution: {
      creator: "Olga Ernst",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Okenyenya_mountain_and_mesas_in_front,_Namibia_(2014).jpg",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  "1138811c-18d8-4258-ba5f-159420bf9563": {
    src: "/content-images/ch4-highland-hd.webp",
    alt: "High Andean country: cultivated slopes and scattered small buildings under a wide sky, with mountains along the horizon",
    width: 1600,
    height: 1200,
    caption: "Andean highland at La Chimba, Ecuador",
    attribution: {
      creator: "TupakAmaruIshkay",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:La_Chimba.jpg",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  "145feea9-9cbf-4aef-a558-55b5cfbf79ea": {
    src: "/content-images/ch4-dunes-hd.webp",
    alt: "Rippled orange sand dunes running to the horizon at sunset, the low sun raking across the crests",
    width: 1600,
    height: 1068,
    caption: "Dunes at Erg Chebbi, Morocco",
    attribution: {
      creator: "Thomas Fuhrmann",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Erg_Chebbi_sunset.jpg",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  "7edee181-e0ff-4b2e-b2e5-6824ec89752b": {
    src: "/content-images/ch4-sea-hd.webp",
    alt: "Open sea running flat to the horizon under a dark sky, with sunlight glinting across the water",
    width: 1600,
    height: 1067,
    caption: "Open sea to the horizon",
    attribution: {
      creator: "Andrej Chudy",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Andrej_Chudy_2015-04-28_(Unsplash_Sp4EL_R1JQk).jpg",
      license: "CC0",
      licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    },
  },
  "d73748a8-24d7-4c3c-832e-cbc546eea9ae": {
    src: "/content-images/ch4-lake-hd.webp",
    alt: "A green mountain lake held in a rocky valley, bare grey slopes rising steeply on both sides",
    width: 1600,
    height: 1067,
    caption: "Badak Lake, Ugam-Chatkal National Park, Uzbekistan",
    attribution: {
      creator: "26D",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Badak_Lake_in_July.jpg",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  "d3433b55-cb3b-4529-8498-4f8cf6f1ac77": {
    src: "/content-images/ch4-reef-hd.webp",
    alt: "A coral reef underwater: branching and boulder corals covering the sea floor in clear blue-green water",
    width: 1600,
    height: 1200,
    caption: "Coral reef off Savai'i, Samoa",
    attribution: {
      creator: "Rickard Törnblad",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Coral_reef_off_the_coast_of_Fagamalo,_Savai%27i,_Samoa_(3)_-_August_2016.jpg",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  "ce182424-77f5-44e9-ba6a-c9a07932cc80": {
    src: "/content-images/ch4-bay-hd.webp",
    alt: "A wide sheltered bay ringed by wooded hills, sailing boats moored across the still water",
    width: 1600,
    height: 1060,
    caption: "The bay of Portoferraio, Elba",
    attribution: {
      creator: "SDKmac",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:2014_Bay_of_Portoferraio.JPG",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  "974cab55-ca48-456d-8048-44d23cb932f1": {
    src: "/content-images/ch4-river-hd.webp",
    alt: "A pale mountain river running fast over boulders through a forested gorge, limestone peaks standing behind",
    width: 1600,
    height: 1068,
    caption: "A mountain river in the Gesäuse, Austria",
    attribution: {
      creator: "Andreas Hollinger",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Andreas_Hollinger-7474_NPG.jpg",
      license: "CC BY 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    },
  },
  "014b51e6-3595-4f81-823b-16f091870b56": {
    src: "/content-images/ch4-fjord-hd.webp",
    alt: "A narrow fjord running between steep green mountain walls, snow on the tops and a waterfall dropping to the water",
    width: 1536,
    height: 1024,
    caption: "Geirangerfjord, Norway",
    attribution: {
      creator: "Unknown photographer",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Geirangerfjorden.jpg",
      license: "Public domain",
    },
  },
  "312f4696-cc12-4c40-bc37-1820bd254fae": {
    src: "/content-images/ch1-p4-topography-hills.jpg",
    alt: "Green rolling hills beneath a broad blue sky with white cumulus clouds",
    width: 971,
    height: 641,
    caption: "Topography — chapter-1.pdf, p4",
    sourceFile: "chapter-1-candidate-a.pdf",
    pageOrSlide: 4,
  },
  "90510d10-b499-478f-b6fa-743d36251648": {
    src: "/content-images/ch1-p6-geography-coast.jpg",
    alt: "Top-down aerial photo of a shoreline, with deep turquoise water, white breaking surf, and warm coral-pink sand",
    width: 2040,
    height: 1530,
    caption: "Why geography matters to tourism — chapter-1.pdf, p6",
    sourceFile: "chapter-1-candidate-a.pdf",
    pageOrSlide: 6,
  },
  "cb85a578-3658-43ce-a7a4-686c75d8b5a2": {
    src: "/content-images/ch1-leisure-hd.webp",
    alt: "People relaxing at a beachside café under pine trees, lounge chairs and umbrellas set out on the sand by the sea",
    width: 1600,
    height: 1067,
    caption: "Free time at a beachside café",
    attribution: {
      creator: "PattayaPatrol",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:DFC_2137_Beachside_pop-up_café_under_pine_trees_with_people_relaxing_on_lounge_chairs_and_umbrellas_by_the_shore.jpg",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  "95b44f13-a11f-472f-bbcb-d40ed359d0ed": {
    src: "/content-images/ch1-p8-recreation-hikers.jpg",
    alt: "Group of hikers with large backpacks walking along a forest trail",
    width: 1800,
    height: 1200,
    caption: "Recreation — chapter-1.pdf, p8",
    sourceFile: "chapter-1-candidate-a.pdf",
    pageOrSlide: 8,
  },
  "68fb52c1-6420-4e3b-917f-dedc31108e5a": {
    src: "/content-images/ch1-p17-push-pull-beach.jpg",
    alt: "Aerial view of a beach with parasols, swimmers, and turquoise water",
    width: 2000,
    height: 1331,
    caption: "Beach tourism scene — chapter-1.pdf, p17",
    sourceFile: "chapter-1-candidate-a.pdf",
    pageOrSlide: 17,
  },
  "b64ba9e3-b0a5-40b5-9b59-2cb8ebccfd6f": {
    src: "/content-images/ch1-p18-push-factors-travellers.jpg",
    alt: "Two travellers with suitcases, a passport, and tickets against a blue background",
    width: 2700,
    height: 1800,
    caption: "Travellers preparing to depart — chapter-1.pdf, p18",
    sourceFile: "chapter-1-candidate-a.pdf",
    pageOrSlide: 18,
  },
  "132c9f68-2e16-430e-b7eb-4ab458b6408b": {
    src: "/content-images/ch1-p19-pull-factors-signpost.jpg",
    alt: "Directional signpost among palm leaves showing destination distances",
    width: 2554,
    height: 1700,
    caption: "Destination distance signpost — chapter-1.pdf, p19",
    sourceFile: "chapter-1-candidate-a.pdf",
    pageOrSlide: 19,
  },
  // --- Source tables and reference maps ------------------------------------
  // Added 2026-08-25 from docs/pedagogy-review-content-units-2026-08-25.md
  // Finding 1. These seven units each transcribe a source *table* into a single
  // run-on sentence — the worst is 71 words with no full stop until the end.
  // The table is the form the source itself used, and it carries rank ordering
  // and per-row values the prose dropped. Restoring it changes no stored prose.
  "c91a07a5-dd5b-4db2-9f5d-3d4e8b56d8ad": {
    src: "/content-images/ch4-p16-mountain-ranges-map.jpg",
    alt: "World relief map titled Mountain Ranges of the World, with coloured markers keyed to ranges grouped by continent. North America: Alaska Range, Appalachian Mountains, Brooks Range, Coastal Mountains, Rocky Mountains, Sierra Madre. South America: Andes. Europe: Alps, Caucasus Mountains, Kjolen Mountains, Pyrenees, Taurus Mountains, Thian Mountains, Ural Mountains. Africa: Atlas Mountains, Crystal Mountains, Drakensberg Mountains, Mitumba Mountains. Asia: Altay Mountains, Himalayan Mountains, Tian Shan, Zagros Mountains. Oceania: Great Dividing Range, Southern Alps.",
    width: 1337,
    height: 925,
    caption: "Mountain ranges of the world — chapter-4.pdf, p16",
    sourceFile: "chapter-4.pdf",
    pageOrSlide: 16,
  },
  "1a02245b-8ca8-474b-9db8-06fc337079b0": {
    src: "/content-images/ch2-midlat-humid-subtropical-hd.webp",
    alt: "Bald cypress forest standing in shallow brown floodwater, wide buttressed trunks and knee roots below a canopy of fresh green leaves",
    width: 1600,
    height: 1067,
    caption: "Bald cypress floodplain forest, Congaree National Park, South Carolina",
    attribution: {
      creator: "Andrew Parlette",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Bald_Cypress_Forest_in_Congaree_National_Park_(52781884863).jpg",
      license: "CC BY 2.0",
      licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    },
  },
  "d9843887-94ef-4915-a787-5ad9f89574a0": {
    src: "/content-images/ch2-midlat-mixed-forest-hd.webp",
    alt: "Forest photographed straight down from the air in autumn: orange, yellow and red broad-leaved crowns with dark green conifers standing among them",
    width: 1600,
    height: 1066,
    caption: "Mixed forest from the air, Quebec",
    attribution: {
      creator: "Gabriel Picard",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Aerial_view_of_mixed_forest_in_Quebec.jpg",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  "5970c2f6-2c0d-46a2-8225-e0e61e135315": {
    src: "/content-images/ch2-highland-scandinavia-hd.webp",
    alt: "Bare, snow-streaked mountains in Jotunheimen, Norway, with treeless brown ground and patches of late snow in the foreground",
    width: 1600,
    height: 900,
    caption: "Jotunheimen, Norway",
    attribution: {
      creator: "Dirk-Jan van Roest",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Jotunheimen_2017.jpg",
      license: "CC BY 2.0",
      licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    },
  },
  "878c9c02-45dc-4f6c-8129-4d380170ed87": {
    src: "/content-images/ch4-tibetan-plateau-hd.webp",
    alt: "The Tibetan Plateau from orbit: a vast tan highland crossed by snow-covered ranges",
    width: 1600,
    height: 1252,
    caption: "Autumn on the Tibetan Plateau, seen from orbit",
    attribution: {
      creator: "MODIS Land Rapid Response Team, NASA GSFC",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Autumn_on_the_Tibetan_Plateau_(MODIS_2025-11-18).jpg",
      license: "Public domain",
    },
  },
  "d1a1ea5b-5513-4f8c-b4aa-db472c36543e": {
    src: "/content-images/ch4-antarctic-plateau-hd.webp",
    alt: "Low wind-carved ridges of snow running across the Antarctic Plateau, a tracked vehicle small on the horizon",
    width: 1600,
    height: 1067,
    caption: "The surface of the Antarctic Plateau",
    attribution: {
      creator: "Stephen Bannister",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Plateau-surface.jpg",
      license: "CC BY 2.5",
      licenseUrl: "https://creativecommons.org/licenses/by/2.5/",
    },
  },
  "1e70ba18-cb53-40d3-a29e-4ec49ceb26d9": {
    src: "/content-images/ch4-hill-hd.webp",
    alt: "A green limestone hill rising steeply out of walled pasture, a lane running past its foot",
    width: 1600,
    height: 900,
    caption: "Chrome Hill in the Peak District, England",
    attribution: {
      creator: "TXGemGem",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Chrome_Hill_and_Pastoral_Landscapes_–_Peak_District_National_Park.jpg",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  "c53e4367-7dec-4941-91c3-c6917f3961bf": {
    src: "/content-images/ch4-mountain-tourism-hd.webp",
    alt: "A group of walkers on a mountain path among autumn larches",
    width: 1600,
    height: 1200,
    caption: "Walkers on a mountain trail in the Zywiec Beskids, Poland",
    attribution: {
      creator: "Marek Ślusarczyk (Tupungato) Photo portfolio",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:039_Beskidy_mountain_in_Poland_-_autumn_hike_in_Beskid_Żywiecki,_złota_polska_jesień.jpg",
      license: "CC BY 3.0",
      licenseUrl: "https://creativecommons.org/licenses/by/3.0/",
    },
  },
  "f2488806-2439-45a2-bfff-e6966b6f1623": {
    src: "/content-images/ch4-gulf-hd.webp",
    alt: "A satellite view of the Persian Gulf: a long arm of green-blue water reaching in between desert coasts",
    width: 1600,
    height: 1147,
    caption: "The Persian Gulf from orbit",
    attribution: {
      creator: "MODIS Land Rapid Response Team, NASA GSFC",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Persian_Gulf_(MODIS_2019-07-25).jpg",
      license: "Public domain",
    },
  },
  "f71a055b-9482-405c-b693-83cb2a9dbbb0": {
    src: "/content-images/ch4-sea-coast-hd.webp",
    alt: "A sandy beach with breakwaters below a grassy slope, open sea running to the horizon",
    width: 1600,
    height: 1062,
    caption: "The Baltic Sea at Rerik, Germany",
    attribution: {
      creator: "Radomianin",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Baltic_Sea_view_from_Schmiedeberg_hill_in_Rerik,_2025-06-23.jpg",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  "14c2ee87-9d53-4daa-ae84-97463e30d7e8": {
    src: "/content-images/ch4-lagoon-hd.webp",
    alt: "Shallow turquoise water enclosed by steep limestone cliffs, a boat at the entrance",
    width: 1600,
    height: 1067,
    caption: "A lagoon in Bacuit Bay, El Nido, Philippines",
    attribution: {
      creator: "Vyacheslav Argenberg",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Island_lagoon_in_Bacuit_Bay,_El_Nido,_Palawan,_Philippines.jpg",
      license: "CC BY 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    },
  },
  "6dd27876-4919-40bb-8f15-21a2468c8029": {
    src: "/content-images/ch4-spring-hd.webp",
    alt: "Water running out among boulders and away downhill as a clear stream",
    width: 1600,
    height: 1067,
    caption: "A spring stream at Chae Son, Lampang, Thailand",
    attribution: {
      creator: "Jomis 9",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Hot_spring_stream_at_Chae_Son_National_Park_Lampang_Thailand_2025.jpg",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  "2b2a285e-1dec-482e-abb0-805e54fb6d97": {
    src: "/content-images/ch4-glacier-hd.webp",
    alt: "A glacier tongue descending between grey mountain walls to a meltwater pool",
    width: 1600,
    height: 728,
    caption: "The Athabasca Glacier, Jasper National Park, Canada",
    attribution: {
      creator: "Ethan Sahagun",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Athabasca_Glacier_from_the_valley_floor,_Jasper_National_Park,_Alberta,_Canada.jpg",
      license: "CC BY 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    },
  },
  "e3ec1403-0a28-46c9-8e43-fef07e290273": {
    src: "/content-images/ch2-tropical-overview-hd.webp",
    alt: "Tall coconut palms leaning over a beach under a bright tropical sky",
    width: 1600,
    height: 1200,
    caption: "Coconut palms on the coast at Sabang, Palawan",
    attribution: {
      creator: "Vyacheslav Argenberg",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Coconut_palm_trees_on_the_beach_of_Sabang,_Palawan,_Philippines.jpg",
      license: "CC BY 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    },
  },
  "a48bde3a-9dbe-4ea1-af69-fdb944d7ff31": {
    src: "/content-images/ch2-dry-overview-hd.webp",
    alt: "An empty road running between bare rocky ridges in the desert",
    width: 1600,
    height: 1067,
    caption: "A road through the desert of southern Sinai, Egypt",
    attribution: {
      creator: "Vyacheslav Argenberg",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Sinai,_Egypt,_Road_through_the_desert_landscape,_rocky_peaks_and_valleys.jpg",
      license: "CC BY 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    },
  },
  "c7aab0d3-88fd-4616-9533-0026fea802b6": {
    src: "/content-images/ch2-highlat-overview-hd.webp",
    alt: "Two people beside equipment on Arctic sea ice, pressure ridges running across it",
    width: 1600,
    height: 1048,
    caption: "The ice pack at the North Pole",
    attribution: {
      creator: "Matti&amp;Keti; Lorenz.King@geogr.uni-giessen.de",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:North_Pole,_Arctic_Ocean,_sea_ice_01.jpg",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  "7e0adbdc-4b43-4296-bb24-f10483072292": {
    src: "/content-images/ch1-grey-tourism-hd.webp",
    alt: "An elderly tourist with a camera round his neck watching a procession of monks in orange robes",
    width: 1600,
    height: 1062,
    caption: "An older visitor watching an alms-giving procession",
    attribution: {
      creator: "shankar s. from Dubai, united arab emirates",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:After_taking_a_picture,_an_elderly_tourist_watches_the_proceedings_(14602518191).jpg",
      license: "CC BY 2.0",
      licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    },
  },
  "6f990b48-e88a-4510-9d84-8c50d263818e": {
    src: "/content-images/ch1-common-interest-hd.webp",
    alt: "A dense crowd of pilgrims filling a street during the Mazu pilgrimage",
    width: 1600,
    height: 1200,
    caption: "The Baishatun Mazu pilgrimage, Taiwan",
    attribution: {
      creator: "Stefsun318",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Mazu_pilgrimage_in_Taiwan.jpg",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  "10f721f6-6e65-4f7c-915b-21ab8d47b895": {
    src: "/content-images/ch1-business-tourism-hd.webp",
    alt: "Visitors walking between exhibition stands in a trade-fair hall",
    width: 1600,
    height: 1067,
    caption: "A consumer fair and trade expo",
    attribution: {
      creator: "Pangalau",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:30th_Consumer_Fair_and_Trade_Expo_03.jpg",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  "00b45e0c-a76f-4d68-8e7c-79942208cb72": {
    src: "/content-images/ch1-holiday-tourism-hd.webp",
    alt: "Rows of beach umbrellas and sunbeds on the sand, inflatable rings stacked in front",
    width: 1600,
    height: 1067,
    caption: "Umbrellas and sunbeds on a resort beach",
    attribution: {
      creator: "PattayaPatrol",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:DFC_4016_Sun-drenched_beach_with_umbrellas_and_colorful_inflatable_rings_stacked_ready_for_a_day_of_fun_by_the_sea.jpg",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  "eef870d4-aa62-4385-ba4e-ca86e292b9c3": {
    src: "/content-images/ch1-tourism-hd.webp",
    alt: "A blue-domed white church and bell tower in Fira, Santorini, above the deep blue caldera with an island beyond",
    width: 1600,
    height: 1067,
    caption: "Fira, Santorini — a destination visitors travel to from outside their usual environment",
    attribution: {
      creator: "kuhnmi",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Blue_Dome_in_Santorini_-_Flickr_-_kuhnmi.jpg",
      license: "CC BY 2.0",
      licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    },
  },
};
