export type ContentImage = {
  src: string;
  alt: string;
  width: number;
  height: number;
  caption?: string;
  sourceFile?: string;
  pageOrSlide?: number;
  attribution?: {
    creator: string;
    sourceUrl: string;
    license: string;
    /** Absent for public-domain works, which have no licence deed to link to. */
    licenseUrl?: string;
  };
};

/**
 * Real photos/figures that support a specific content unit,
 * keyed by content_unit id. Rendered inside that specific ContentUnit card
 * (unlike topicDiagrams in diagrams.ts, which is one figure per topic).
 * Course-source images record their source file and page. Openly licensed
 * supporting photos must record creator, source URL, and licence attribution.
 */
export const contentImages: Record<string, ContentImage> = {
  "53ea1015-3e72-4d7f-867e-77f2ca172e82": {
    src: "/content-images/ch4-p24-atoll.png",
    alt: "Aerial photo of an atoll — a ring-shaped coral reef enclosing a pale turquoise lagoon",
    width: 300,
    height: 185,
    caption: "Atoll — chapter-4.pdf, p24",
    sourceFile: "chapter-4.pdf",
    pageOrSlide: 24,
  },
  "971fd72e-38c8-473b-96ef-b1c7c8204d53": {
    src: "/content-images/ch4-p24-island-cays.png",
    alt: "Aerial photo of a small green vegetated island fringed by white sand in turquoise shallows",
    width: 295,
    height: 180,
    caption: "Island & Cays — chapter-4.pdf, p24",
    sourceFile: "chapter-4.pdf",
    pageOrSlide: 24,
  },
  "ae492e89-3265-45c4-8d4d-838761569a4d": {
    src: "/content-images/ch4-p24-island-cays.png",
    alt: "Aerial photo of a small vegetated island fringed by sandy cays and coral reef in turquoise shallows",
    width: 295,
    height: 180,
    caption: "Island & Cays — chapter-4.pdf, p24",
    sourceFile: "chapter-4.pdf",
    pageOrSlide: 24,
  },
  "8bb2eaca-0afd-45c8-8ecb-d9a3d0209a99": {
    src: "/content-images/ch4-p24-peninsula.png",
    alt: "Aerial photo of a green peninsula jutting into dark blue sea, with a snow-capped mountain range behind it",
    width: 300,
    height: 180,
    caption: "Peninsula / Foreland — chapter-4.pdf, p24",
    sourceFile: "chapter-4.pdf",
    pageOrSlide: 24,
  },
  "ab312ce7-5f79-4740-a227-ac4c0e3bc6ef": {
    src: "/content-images/ch3-p3-latitude-globe.jpg",
    alt: "Labelled globe diagram showing the North Pole, Arctic Circle, Tropic of Cancer, Equator, Tropic of Capricorn, Antarctic Circle, and South Pole",
    width: 550,
    height: 384,
    caption: "Latitude — chapter-3.pdf, p3",
    sourceFile: "chapter-3.pdf",
    pageOrSlide: 3,
  },
  "04c61a82-dd00-40f8-a954-3bce4182d47c": {
    src: "/content-images/ch3-p4-longitude-globe.jpg",
    alt: "Globe diagram showing longitude meridian lines converging at the poles, labelled with degrees east and west and the Prime Meridian",
    width: 320,
    height: 312,
    caption: "Longitude — chapter-3.pdf, p4",
    sourceFile: "chapter-3.pdf",
    pageOrSlide: 4,
  },
  "2aa381ff-f92f-4fcd-8dec-43674a4f0903": {
    src: "/content-images/ch3-greenwich-clock-hd.webp",
    alt: "The Shepherd Gate clock at the Royal Observatory, Greenwich: a 24-hour dial set into a brick wall, its single hand pointing to the hour, lettered Shepherd Patentee and Galvano-Magnetic Clock",
    width: 1600,
    height: 1424,
    caption: "The Shepherd Gate clock at the Royal Observatory, Greenwich — the public face of Greenwich Mean Time",
    attribution: {
      creator: "Alvesgaspar",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Greenwich_clock_1-manipulated.jpg",
      license: "CC BY-SA 3.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    },
  },
  "6fd79ae0-63ed-4a1c-972d-091ac7e688cb": {
    src: "/content-images/ch3-p7-prime-meridian.jpg",
    alt: "First-person photo of two feet straddling the Prime Meridian line embedded in the pavement at the Royal Observatory, Greenwich, with brass plaques giving real longitudes for cities on each side",
    width: 500,
    height: 375,
    caption: "Standing on the Prime Meridian — chapter-3.pdf, p7",
    sourceFile: "chapter-3.pdf",
    pageOrSlide: 7,
  },
  "a6943945-1c7c-4ea8-a5b2-2552428119bc": {
    src: "/content-images/ch3-p10-time-zone-map.jpg",
    alt: "World time zone map with a row of clock faces from noon to midnight, colour-banded time zones, the Greenwich Meridian, and the International Date Line marked between Sunday and Monday",
    width: 839,
    height: 495,
    caption: "World time zones and the International Date Line — chapter-3.pdf, p10",
    sourceFile: "chapter-3.pdf",
    pageOrSlide: 10,
  },
  "3868dc9c-a755-441c-9920-c385a6b86634": {
    src: "/content-images/ch1-p13-plaza-de-espana.jpg",
    alt: "Plaza de España, Seville — a semicircular brick-and-ceramic palace with towers, a canal, and an ornate tiled bridge",
    width: 900,
    height: 600,
    caption: "Plaza de España, Seville — chapter-1.pdf, p13",
    sourceFile: "chapter-1-candidate-a.pdf",
    pageOrSlide: 13,
  },
  "25f51ac3-0193-4428-a2a7-a1031cfdef6e": {
    src: "/content-images/ch1-p14-kl-skyline.jpg",
    alt: "Kuala Lumpur skyline at night, with the illuminated Petronas Twin Towers at centre",
    width: 900,
    height: 521,
    caption: "Kuala Lumpur skyline — chapter-1.pdf, p14",
    sourceFile: "chapter-1-candidate-a.pdf",
    pageOrSlide: 14,
  },
  "a92b84df-02e5-4635-872c-507863427545": {
    src: "/content-images/ch1-p15-travel-route.jpg",
    alt: "An empty straight two-lane road running to a vanishing point between golden crop fields",
    width: 960,
    height: 659,
    caption: "Travel routes — chapter-1.pdf, p15",
    sourceFile: "chapter-1-candidate-a.pdf",
    pageOrSlide: 15,
  },
  "571f3d66-5474-4ad0-8479-56c06e609134": {
    src: "/content-images/ch1-p30-hagia-sophia.jpg",
    alt: "Hagia Sophia and the Sultanahmet district, Istanbul, at dusk, with a tree-lined promenade in the foreground",
    width: 795,
    height: 445,
    caption: "Hagia Sophia, Istanbul — chapter-1.pdf, p30 (photo credit: CrescentRating)",
    sourceFile: "chapter-1-candidate-a.pdf",
    pageOrSlide: 30,
  },
  "11b8ee9b-269a-49f1-b1c1-571951ce1e81": {
    src: "/content-images/ch2-midlat-mediterranean-hd.webp",
    alt: "Tuscan hillside in summer: rows of vines and grey-green olive groves on dry slopes, with dark upright cypresses and a hill village in the haze beyond",
    width: 1600,
    height: 1067,
    caption: "Olive groves, vines and cypresses in Chianti, Tuscany",
    attribution: {
      creator: "bongo vongo",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Olive_groves,_grape_vines_and_cypresses_in_Chiantishire_(4054460424).jpg",
      license: "CC BY-SA 2.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    },
  },
  "fc62a899-7a5c-4f04-b075-372d5c735849": {
    src: "/content-images/ch2-midlat-marine-west-coast-hd.webp",
    alt: "Temperate rainforest floor in the Hoh valley, where fallen logs, standing trunks and low branches are all thickly covered in bright green moss and ferns",
    width: 1600,
    height: 1029,
    caption: "Moss-covered temperate rainforest, Hoh valley, Olympic National Park, Washington",
    attribution: {
      creator: "Olympic National Park (NPS)",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Hoh_Rainforest,_mossy_log_tree_NPS_Photo_(16680304244).jpg",
      license: "Public domain",
    },
  },
  "856b9788-22cc-4435-9231-654443412c72": {
    src: "/content-images/ch2-midlat-humid-continental-hd.webp",
    alt: "A frozen reservoir under deep snow, ringed by snow-laden conifers, with snow-capped mountains on the far shore under a clear winter sky",
    width: 1600,
    height: 1200,
    caption: "Chittenden Reservoir frozen over, Green Mountain National Forest, Vermont",
    attribution: {
      creator: "USDA Forest Service",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Green_Mountain_National_Forest_(20241222-FS-GM-BME-ChittendenReservoir-001).jpg",
      license: "Public domain",
    },
  },
  "0e07433e-b0f7-442f-a49a-0e2515a3f401": {
    src: "/content-images/ch2-p13-climate-zones-by-latitude.jpg",
    alt: "World map banded into five horizontal climate zones — Arctic, Mid-latitudes, Tropics, Mid-latitudes, Antarctic — each labelled with its season count",
    width: 700,
    height: 421,
    caption: "Climate zones by latitude — chapter-2.pdf, p13",
    sourceFile: "chapter-2.pdf",
    pageOrSlide: 13,
  },
  "0cf701f8-8fde-407e-ae4f-d532dab52975": {
    src: "/content-images/ch2-tropical-rainforest-hd.webp",
    alt: "Dense, layered primary tropical rainforest covering the limestone hills of Khao Sok in southern Thailand",
    width: 1600,
    height: 1067,
    caption: "Primary tropical rainforest in Khao Sok, southern Thailand",
    attribution: {
      creator: "Vyacheslav Argenberg",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Khao_Sok_primary_tropical_rainforest,_southern_Thailand.jpg",
      license: "CC BY 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    },
  },
  "82c13fdc-c0c5-46d7-9320-d2cf89f273fc": {
    src: "/content-images/ch2-summer-monsoon-hd.webp",
    alt: "Heavy summer monsoon clouds and rain over a waterlogged green landscape with mountains in the distance",
    width: 1600,
    height: 898,
    caption: "Moist summer-monsoon conditions",
    attribution: {
      creator: "lensnmatter",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Monsoon_(36877269620).jpg",
      license: "CC BY 2.0",
      licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    },
  },
  "c31bc5c9-c35d-4686-af03-166c4ff45227": {
    src: "/content-images/ch2-winter-monsoon-hd.webp",
    alt: "Northern Thai valley in the dry season: the Nan River reduced to a narrow stream across a wide gravel bed, with harvested paddy terraces and haze over the hills",
    width: 1600,
    height: 1000,
    caption: "Dry-season conditions in Nan Province, Thailand, photographed in December — the Nan River near its source, barely more than a stream",
    attribution: {
      creator: "Takeaway",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:2013_Chaloem_Phra_Kiat_District_Nan.jpg",
      license: "CC BY-SA 3.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    },
  },
  "5991f254-816b-4035-ab43-1f911804a967": {
    src: "/content-images/ch2-tropical-savanna-hd.webp",
    alt: "Open Serengeti grassland dotted with flat-topped acacia trees beneath a broad blue sky",
    width: 1600,
    height: 922,
    caption: "Tropical savanna in Serengeti National Park, Tanzania",
    attribution: {
      creator: "Bjørn Christian Tørrissen",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Serengeti-Landscape-2012.JPG",
      license: "CC BY-SA 3.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    },
  },
  "27a0eeb9-953f-4ac7-9e86-55d9e8789006": {
    src: "/content-images/ch2-dry-oasis-hd.webp",
    alt: "Timimoun oasis in the Algerian desert, with water and dense date palms surrounded by arid terrain",
    width: 1280,
    height: 960,
    caption: "Oasis at Timimoun in the Algerian desert",
    attribution: {
      creator: "Taguelmoust",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Oasis_timimoun.png",
      license: "CC BY-SA 3.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    },
  },
  "3351e87e-e9ef-44f4-bb9e-25d1b334cdde": {
    src: "/content-images/ch2-dry-steppe-hd.webp",
    alt: "Treeless Eurasian steppe in Inner Mongolia, with extensive grassland beneath a wide sky",
    width: 1600,
    height: 1200,
    caption: "Eurasian steppe grassland in Inner Mongolia",
    attribution: {
      creator: "Shizhao",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Grasslands-menggu.JPG",
      license: "CC BY-SA 3.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    },
  },
  "f1012de4-075c-4ab5-a441-1cfb3a871732": {
    src: "/content-images/ch2-midlat-deciduous-forest-hd.webp",
    alt: "Steep valley sides blanketed in broad-leaved forest turning orange, red and gold in autumn, with a stream in the shaded valley floor",
    width: 1600,
    height: 1067,
    caption: "Deciduous forest in autumn colour, Jogakura Valley, Hakkoda Mountains, Japan",
    attribution: {
      creator: "lumoplank",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Hakkoda_Mountains,_Part_III-_Jogakura_Valley_-_Hakkoda6899.jpg",
      license: "CC0",
      licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    },
  },
  "597fd168-ea69-4012-be79-c730070b952f": {
    src: "/content-images/ch2-midlat-evergreen-forest-hd.webp",
    alt: "Stand of tall pines with straight bare trunks and needled crowns high above, over a green ground cover of bilberry and lichen",
    width: 1600,
    height: 1200,
    caption: "Coniferous forest near the Svartalven river, Sweden",
    attribution: {
      creator: "Leonhard Lenz",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Coniferous_forest_in_Sweden_near_the_Svart%C3%A4lven_river_01.jpg",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  "6e94cafe-6b33-451f-9f77-a41ce89f09e5": {
    src: "/content-images/ch2-highlat-subarctic-hd.webp",
    alt: "Dense dark coniferous taiga covering hills around a small lake, with low scrub in the foreground and no broad-leaved trees",
    width: 1600,
    height: 1067,
    caption: "Siberian taiga, Ergaki Range, Krasnoyarsk Krai, Russia",
    attribution: {
      creator: "Vyacheslav Argenberg",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Ergaki,_Taiga_in_Siberia,_Coniferous_forest,_Sayan_Mountains,_Siberia,_Russia.jpg",
      license: "CC BY 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    },
  },
  "e6f73628-6399-476a-aa9e-75fd75b98944": {
    src: "/content-images/ch2-highlat-tundra-hd.webp",
    alt: "Treeless Arctic tundra in autumn: scarlet and gold low shrubs, mosses and lichen over rock, with only a few stunted birches and a bare ridge behind",
    width: 1600,
    height: 1067,
    caption: "Arctic tundra in autumn colour, Kola Peninsula, Russia",
    attribution: {
      creator: "Artem Abdukakharov",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Arctic_tundra_in_autumn_colors_near_lake_Lovozero_in_Murmansk_Oblast,_Russia.jpg",
      license: "CC BY 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    },
  },
  "7327549a-dc74-470d-9274-80fdfc13506b": {
    src: "/content-images/ch2-highlat-ice-cap-hd.webp",
    alt: "The Greenland ice sheet from an aircraft: an unbroken white surface of ice stretching to the horizon, breaking into crevasses where it meets bare coastal rock",
    width: 1600,
    height: 1089,
    caption: "The Greenland ice sheet, seen from the air over the east coast",
    attribution: {
      creator: "Hannes Grobe",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Greenland-ice_sheet_hg.jpg",
      license: "CC BY-SA 2.5",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/2.5/",
    },
  },
  "7bc6947d-0d4c-441a-817c-77284ad40069": {
    src: "/content-images/ch2-highland-treeline-hd.webp",
    alt: "Mount Hood above its tree line: conifers grow in the foreground and then stop, leaving bare rock, scree and snowfields on the peak above",
    width: 1600,
    height: 1217,
    caption: "The tree line on Mount Hood, Oregon: forest below, bare rock and snow above",
    attribution: {
      creator: "inkknife_2000",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Mount_Hood_Tree_Line,_OR_8-13_(16171629489).jpg",
      license: "CC BY-SA 2.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    },
  },
  "15c93c2f-a904-4d1b-bec5-6275c231cf68": {
    src: "/content-images/ch4-p2-nature-tourists.jpg",
    alt: "A group of nature tourists in a sunlit clearing with tripods, spotting scopes, binoculars, and cameras trained into the trees",
    width: 1460,
    height: 2189,
    caption: "Nature-based tourism — chapter-4.pdf, p2",
    sourceFile: "chapter-4.pdf",
    pageOrSlide: 2,
  },
  "0da062ff-1e92-42bb-bfd1-e5617f5764bf": {
    src: "/content-images/ch4-p3-hand-mountain.jpg",
    alt: "A first-person view of an open hand and forearm outstretched toward a forested mountain ridge",
    width: 1800,
    height: 1200,
    caption: "Recognizing a landscape as a tourism resource — chapter-4.pdf, p3",
    sourceFile: "chapter-4.pdf",
    pageOrSlide: 3,
  },
  "2d67b8a0-9232-4918-9b10-9570fa80f03e": {
    src: "/content-images/ch4-p9-hiker-lake.jpg",
    alt: "A hiker with a large backpack standing on a lakeside boardwalk, facing a still green-blue alpine lake ringed by dense conifer forest",
    width: 1728,
    height: 1152,
    caption: "Natural landscape — chapter-4.pdf, p9",
    sourceFile: "chapter-4.pdf",
    pageOrSlide: 9,
  },
  "a46327c7-105d-4034-b217-620132142f42": {
    src: "/content-images/ch4-p10-waterfall.jpg",
    alt: "A waterfall dropping through dark wet rock into a plunge pool surrounded by moss and ferns",
    width: 1160,
    height: 870,
    caption: "Waterfall — chapter-4.pdf, p10",
    sourceFile: "chapter-4.pdf",
    pageOrSlide: 10,
  },
  "d0887588-5176-4ed4-bc95-b7658bc61ac1": {
    src: "/content-images/ch4-p14-kinabalu-signboard.png",
    alt: "Three climbers celebrating at the Low's Peak summit signboard on Mount Kinabalu, reading TAMAN KINABALU / LOW'S PEAK (4,095.2 M)",
    width: 505,
    height: 375,
    caption: "Mount Kinabalu summit, Low's Peak — chapter-4.pdf, p14",
    sourceFile: "chapter-4.pdf",
    pageOrSlide: 14,
  },
  "e55a19ac-f045-454e-9a37-786b141b5ddd": {
    src: "/content-images/ch4-p17-plateau-city.png",
    alt: "A wooded ridge in the foreground looking down onto a city sprawling across a flat valley floor with mountains behind",
    width: 488,
    height: 200,
    caption: "Plateau — chapter-4.pdf, p17",
    sourceFile: "chapter-4.pdf",
    pageOrSlide: 17,
  },
  "1138811c-18d8-4258-ba5f-159420bf9563": {
    src: "/content-images/ch4-p17-andean-highland.png",
    alt: "Rolling brown-green highland with a snow-capped ridge on the skyline and a scatter of small white buildings on the slope",
    width: 512,
    height: 197,
    caption: "Andean Plateau (altiplano) — chapter-4.pdf, p17",
    sourceFile: "chapter-4.pdf",
    pageOrSlide: 17,
  },
  "145feea9-9cbf-4aef-a558-55b5cfbf79ea": {
    src: "/content-images/ch4-p18-sand-dunes.png",
    alt: "Rippled pale-gold sand dunes with a dark rocky escarpment behind under a bright sky",
    width: 538,
    height: 175,
    caption: "Desert — chapter-4.pdf, p18",
    sourceFile: "chapter-4.pdf",
    pageOrSlide: 18,
  },
  "7edee181-e0ff-4b2e-b2e5-6824ec89752b": {
    src: "/content-images/ch4-p20-sea-horizon.png",
    alt: "A tropical sea horizon with bands of pale turquoise shallows and deeper blue water under a towering white cumulus bank",
    width: 438,
    height: 212,
    caption: "Ocean — chapter-4.pdf, p20",
    sourceFile: "chapter-4.pdf",
    pageOrSlide: 20,
  },
  "d73748a8-24d7-4c3c-832e-cbc546eea9ae": {
    src: "/content-images/ch4-p21-lake.png",
    alt: "A still woodland pond reflecting bright green foliage, with fallen logs and reeds along the near edge",
    width: 550,
    height: 212,
    caption: "Lake — chapter-4.pdf, p21",
    sourceFile: "chapter-4.pdf",
    pageOrSlide: 21,
  },
  "d3433b55-cb3b-4529-8498-4f8cf6f1ac77": {
    src: "/content-images/ch4-p25-coral-reef.png",
    alt: "A colourful coral reef aquarium scene with fish and varied coral formations",
    width: 300,
    height: 190,
    caption: "Coral reef — chapter-4.pdf, p25",
    sourceFile: "chapter-4.pdf",
    pageOrSlide: 25,
  },
  "ce182424-77f5-44e9-ba6a-c9a07932cc80": {
    src: "/content-images/ch4-p25-bay.png",
    alt: "A small sandy cove sheltered by rocky headlands, with green clifftop grass in the foreground",
    width: 300,
    height: 190,
    caption: "Bay — chapter-4.pdf, p25",
    sourceFile: "chapter-4.pdf",
    pageOrSlide: 25,
  },
  "974cab55-ca48-456d-8048-44d23cb932f1": {
    src: "/content-images/ch4-p25-river.png",
    alt: "A forest river tumbling over grey boulders between dark green conifers",
    width: 300,
    height: 185,
    caption: "River — chapter-4.pdf, p25",
    sourceFile: "chapter-4.pdf",
    pageOrSlide: 25,
  },
  "014b51e6-3595-4f81-823b-16f091870b56": {
    src: "/content-images/ch4-p25-fiord.png",
    alt: "A narrow fjord inlet between two green mountain slopes under a clear blue sky",
    width: 300,
    height: 185,
    caption: "Fiord — chapter-4.pdf, p25",
    sourceFile: "chapter-4.pdf",
    pageOrSlide: 25,
  },
  "312f4696-cc12-4c40-bc37-1820bd254fae": {
    src: "/content-images/ch1-p4-topography-hills.jpg",
    alt: "Green rolling hills beneath a broad blue sky with white cumulus clouds",
    width: 971,
    height: 641,
    caption: "Topography — chapter-1.pdf, p4",
    sourceFile: "chapter-1-candidate-a.pdf",
    pageOrSlide: 4,
  },
  "90510d10-b499-478f-b6fa-743d36251648": {
    src: "/content-images/ch1-p6-geography-coast.jpg",
    alt: "Top-down aerial photo of a shoreline, with deep turquoise water, white breaking surf, and warm coral-pink sand",
    width: 2040,
    height: 1530,
    caption: "Why geography matters to tourism — chapter-1.pdf, p6",
    sourceFile: "chapter-1-candidate-a.pdf",
    pageOrSlide: 6,
  },
  "cb85a578-3658-43ce-a7a4-686c75d8b5a2": {
    src: "/content-images/ch1-p7-leisure-seaside.jpg",
    alt: "Woman seen from behind with arms outstretched toward a calm turquoise sea, carrying a straw bag with red flowers",
    width: 1143,
    height: 1714,
    caption: "Leisure — chapter-1.pdf, p7",
    sourceFile: "chapter-1-candidate-a.pdf",
    pageOrSlide: 7,
  },
  "95b44f13-a11f-472f-bbcb-d40ed359d0ed": {
    src: "/content-images/ch1-p8-recreation-hikers.jpg",
    alt: "Group of hikers with large backpacks walking along a forest trail",
    width: 1800,
    height: 1200,
    caption: "Recreation — chapter-1.pdf, p8",
    sourceFile: "chapter-1-candidate-a.pdf",
    pageOrSlide: 8,
  },
  "68fb52c1-6420-4e3b-917f-dedc31108e5a": {
    src: "/content-images/ch1-p17-push-pull-beach.jpg",
    alt: "Aerial view of a beach with parasols, swimmers, and turquoise water",
    width: 2000,
    height: 1331,
    caption: "Beach tourism scene — chapter-1.pdf, p17",
    sourceFile: "chapter-1-candidate-a.pdf",
    pageOrSlide: 17,
  },
  "b64ba9e3-b0a5-40b5-9b59-2cb8ebccfd6f": {
    src: "/content-images/ch1-p18-push-factors-travellers.jpg",
    alt: "Two travellers with suitcases, a passport, and tickets against a blue background",
    width: 2700,
    height: 1800,
    caption: "Travellers preparing to depart — chapter-1.pdf, p18",
    sourceFile: "chapter-1-candidate-a.pdf",
    pageOrSlide: 18,
  },
  "132c9f68-2e16-430e-b7eb-4ab458b6408b": {
    src: "/content-images/ch1-p19-pull-factors-signpost.jpg",
    alt: "Directional signpost among palm leaves showing destination distances",
    width: 2554,
    height: 1700,
    caption: "Destination distance signpost — chapter-1.pdf, p19",
    sourceFile: "chapter-1-candidate-a.pdf",
    pageOrSlide: 19,
  },
  // --- Source tables and reference maps ------------------------------------
  // Added 2026-08-25 from docs/pedagogy-review-content-units-2026-08-25.md
  // Finding 1. These seven units each transcribe a source *table* into a single
  // run-on sentence — the worst is 71 words with no full stop until the end.
  // The table is the form the source itself used, and it carries rank ordering
  // and per-row values the prose dropped. Restoring it changes no stored prose.
  "10376fc0-3ac2-4747-9972-c64ab1e089d4": {
    src: "/content-images/ch4-p15-highest-mountains-table.png",
    alt: "Ranked table of the world's six highest mountains, with height in metres and feet, range and coordinates. 1 Mount Everest / Sagarmatha / Chomolungma, 8,848 m (29,029 ft), Mahalangur Himalaya. 2 K2 / Qogir / Godwin Austen, 8,611 m (28,251 ft), Baltoro Karakoram. 3 Kangchenjunga, 8,586 m (28,169 ft), Kangchenjunga Himalaya. 4 Lhotse, 8,516 m (27,940 ft), Mahalangur Himalaya. 5 Makalu, 8,485 m (27,838 ft), Mahalangur Himalaya. 6 Cho Oyu, 8,201 m (26,864 ft), Mahalangur Himalaya.",
    width: 1387,
    height: 837,
    caption: "List of highest mountains in the world — chapter-4.pdf, p15",
    sourceFile: "chapter-4.pdf",
    pageOrSlide: 15,
  },
  "c91a07a5-dd5b-4db2-9f5d-3d4e8b56d8ad": {
    src: "/content-images/ch4-p16-mountain-ranges-map.jpg",
    alt: "World relief map titled Mountain Ranges of the World, with coloured markers keyed to ranges grouped by continent. North America: Alaska Range, Appalachian Mountains, Brooks Range, Coastal Mountains, Rocky Mountains, Sierra Madre. South America: Andes. Europe: Alps, Caucasus Mountains, Kjolen Mountains, Pyrenees, Taurus Mountains, Thian Mountains, Ural Mountains. Africa: Atlas Mountains, Crystal Mountains, Drakensberg Mountains, Mitumba Mountains. Asia: Altay Mountains, Himalayan Mountains, Tian Shan, Zagros Mountains. Oceania: Great Dividing Range, Southern Alps.",
    width: 1337,
    height: 925,
    caption: "Mountain ranges of the world — chapter-4.pdf, p16",
    sourceFile: "chapter-4.pdf",
    pageOrSlide: 16,
  },
  "0e758a6f-0982-4546-a408-12056d168c5b": {
    src: "/content-images/ch4-p18-largest-deserts-table.png",
    alt: "Ranked table titled The largest deserts, giving area in square kilometres and square miles. 1 Antarctic Desert (Antarctica), 13,829,430 km2. 2 Sahara (Africa), 9,100,000+ km2. 3 Arabian Desert (Middle East), 2,330,000 km2. 4 Gobi Desert (Asia), 1,300,000 km2. 5 Kalahari Desert (Africa), 900,000 km2. 6 Patagonian Desert (South America), 670,000 km2. 7 Great Victoria Desert (Australia), 647,000 km2. 8 Syrian Desert (Middle East), 520,000 km2. 9 Great Basin Desert (North America), 492,000 km2.",
    width: 1225,
    height: 547,
    caption: "The largest deserts — chapter-4.pdf, p18",
    sourceFile: "chapter-4.pdf",
    pageOrSlide: 18,
  },
  "dbdbc094-1f0b-4804-a65a-7f118991f5f1": {
    src: "/content-images/ch4-p19-continental-landmasses-table.png",
    alt: "Ranked table titled Continental landmasses, giving each land mass's highest point and the country containing it. 1 Afro-Eurasia, Mount Everest, 8,848 m (29,029 ft), Nepal and China. 2 Americas, Aconcagua, 6,962 m (22,841 ft), Argentina. 3 Antarctica, Vinson Massif, 4,892 m (16,050 ft), no country. 4 Australia, Mount Kosciuszko, 2,228 m (7,310 ft), Australia.",
    width: 860,
    height: 208,
    caption: "Continental landmasses — chapter-4.pdf, p19",
    sourceFile: "chapter-4.pdf",
    pageOrSlide: 19,
  },
  "647e35d5-2d4c-4a48-a26c-ae943eb83085": {
    src: "/content-images/ch4-p19-highest-island-peaks-table.png",
    alt: "Ranked table titled All highest points over 2,000 m, listing islands by their highest peak. 1 New Guinea, Puncak Jaya, 4,884 m (16,024 ft), Indonesia, island shared with Papua New Guinea. 2 Hawaii, Mauna Kea, 4,205 m (13,796 ft), United States. 3 Borneo, Mount Kinabalu, 4,095 m (13,435 ft), Malaysia, island shared with Brunei and Indonesia. 4 Taiwan, Jade Mountain (Yu Shan), 3,952 m (12,966 ft), Republic of China (Taiwan). 5 Sumatra, Mount Kerinci, 3,805 m (12,484 ft), Indonesia.",
    width: 1255,
    height: 368,
    caption: "All highest points over 2,000 m — chapter-4.pdf, p19",
    sourceFile: "chapter-4.pdf",
    pageOrSlide: 19,
  },
  "0b0aa4a1-67fa-484f-9dce-f385fdf71e91": {
    src: "/content-images/ch4-p20-largest-bodies-of-water-table.png",
    alt: "Ranked table of the ten largest bodies of water by area, in square miles and square kilometres. 1 Pacific Ocean, 64,196,000 sq mi. 2 Atlantic Ocean, 33,400,000. 3 Indian Ocean, 28,400,000. 4 Arctic Ocean, 5,100,000. 5 Arabian Sea, 1,491,000. 6 South China Sea, 1,148,000. 7 Caribbean Sea, 971,000. 8 Mediterranean Sea, 969,000. 9 Bering Sea, 873,000. 10 Bay of Bengal, 838,612.",
    width: 775,
    height: 875,
    caption: "Largest bodies of water by area — chapter-4.pdf, p20",
    sourceFile: "chapter-4.pdf",
    pageOrSlide: 20,
  },
  "1a02245b-8ca8-474b-9db8-06fc337079b0": {
    src: "/content-images/ch2-midlat-humid-subtropical-hd.webp",
    alt: "Bald cypress forest standing in shallow brown floodwater, wide buttressed trunks and knee roots below a canopy of fresh green leaves",
    width: 1600,
    height: 1067,
    caption: "Bald cypress floodplain forest, Congaree National Park, South Carolina",
    attribution: {
      creator: "Andrew Parlette",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Bald_Cypress_Forest_in_Congaree_National_Park_(52781884863).jpg",
      license: "CC BY 2.0",
      licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    },
  },
  "d9843887-94ef-4915-a787-5ad9f89574a0": {
    src: "/content-images/ch2-midlat-mixed-forest-hd.webp",
    alt: "Forest photographed straight down from the air in autumn: orange, yellow and red broad-leaved crowns with dark green conifers standing among them",
    width: 1600,
    height: 1066,
    caption: "Mixed forest from the air, Quebec",
    attribution: {
      creator: "Gabriel Picard",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Aerial_view_of_mixed_forest_in_Quebec.jpg",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  "5970c2f6-2c0d-46a2-8225-e0e61e135315": {
    src: "/content-images/ch2-highland-scandinavia-hd.webp",
    alt: "Bare, snow-streaked mountains in Jotunheimen, Norway, with treeless brown ground and patches of late snow in the foreground",
    width: 1600,
    height: 900,
    caption: "Jotunheimen, Norway",
    attribution: {
      creator: "Dirk-Jan van Roest",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Jotunheimen_2017.jpg",
      license: "CC BY 2.0",
      licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    },
  },
};
