#!/usr/bin/env python3
"""Sample the base map into a coarse grid of land points, for drawing a globe.

The Chapter 3 globe is drawn rather than photographed: an orthographic projection
computed in the browser, so it can be turned. That needs land in a form that can be
projected on the fly, and a raster cannot be. This samples the CC0 base map on a
regular grid and emits the land points as longitude/latitude pairs.

The grid is deliberately coarse. It is not a coastline — it is enough dots to make the
continents recognisable while the globe turns, at a size a phone can redraw at 60fps.

Run:  ./.venv/Scripts/python.exe scripts/build_land_dots.py
"""
import math
import pathlib

from PIL import Image

ROOT = pathlib.Path(__file__).resolve().parent.parent
BASE = ROOT / "web/public/diagrams/ch3-world-basemap.webp"
TARGET = ROOT / "web/src/lib/course-brain/land-dots.ts"

STEP = 2.5  # degrees between samples
LAND_RED_MIN = 200


def main() -> None:
    image = Image.open(BASE).convert("RGB")
    width, height = image.size
    pixels = image.load()

    points: list[tuple[float, float]] = []
    latitude = 90.0 - STEP / 2
    while latitude > -90.0:
        # Meridians converge, so a fixed longitude step bunches the dots into arcs near the
        # poles. Widening the step by 1/cos(latitude) keeps them evenly spread on the sphere.
        longitude_step = STEP / max(math.cos(math.radians(latitude)), 0.12)
        longitude = -180.0 + longitude_step / 2
        while longitude < 180.0:
            x = min(width - 1, max(0, round((longitude + 180.0) / 360.0 * width)))
            y = min(height - 1, max(0, round((90.0 - latitude) / 180.0 * height)))
            if pixels[x, y][0] >= LAND_RED_MIN:
                points.append((round(longitude, 2), round(latitude, 2)))
            longitude += longitude_step
        latitude -= STEP

    # Flat array of lon, lat pairs: half the tokens of a nested one, and the component
    # walks it two at a time.
    flat = ", ".join(f"{lon}, {lat}" for lon, lat in points)
    TARGET.write_text(
        "/**\n"
        f" * Land sampled from the CC0 base map on a {STEP}-degree grid, as flat longitude,\n"
        " * latitude pairs. Generated by scripts/build_land_dots.py — do not edit by hand.\n"
        " *\n"
        " * These are dots, not a coastline. The globe projects them as it turns, which a\n"
        " * raster map cannot do, and at this spacing the continents stay recognisable while\n"
        " * staying cheap enough to redraw on every frame of a drag.\n"
        " */\n"
        f"export const LAND_DOTS: number[] = [{flat}];\n",
        encoding="utf-8",
    )
    print(f"{len(points)} land points at {STEP}° spacing -> {TARGET.relative_to(ROOT)}")
    print(f"file size: {TARGET.stat().st_size // 1024} KB")


if __name__ == "__main__":
    main()
