#!/usr/bin/env python3
"""Regenerate web/public/content-images/ATTRIBUTION.md from content-images.ts.

`content-images.ts` is the single source of truth for what the app actually renders,
so the credit file is generated from it rather than maintained alongside it. A test
(`web/src/lib/course-brain/visual-maps.test.ts`) fails if an attributed image is
missing from the generated table, which is what stops the two drifting apart.

Run after adding or replacing any non-deck image:
    python scripts/build_image_attribution.py
"""
import pathlib
import re
import urllib.parse

ROOT = pathlib.Path(__file__).resolve().parent.parent
SOURCE = ROOT / "web/src/lib/course-brain/content-images.ts"
COMPONENT_SOURCE = ROOT / "web/src/lib/course-brain/component-assets.ts"
TARGET = ROOT / "web/public/content-images/ATTRIBUTION.md"

HEADER = """# Openly licensed supporting images

These Chapter 2 photographs supplement the approved course content. They were
resized and converted to WebP without semantic alteration. Every file listed here
is also declared in `src/lib/course-brain/content-images.ts`, and a test fails if
an attributed image is missing from this table.

Generated by `scripts/build_image_attribution.py` — edit the TypeScript, not this file.

| Local asset | Creator | Source | Licence |
| --- | --- | --- | --- |
"""

COMPONENT_HEADER = """

## Assets belonging to interactive components

Declared in `src/lib/course-brain/component-assets.ts` rather than bound to a content unit.

| Local asset | Creator | Source | Licence |
| --- | --- | --- | --- |
"""

ENTRY_RE = re.compile(r'^  "[0-9a-f-]{36}": \{\n(.*?)^  \},$', re.S | re.M)


def main():
    text = SOURCE.read_text(encoding="utf-8")
    rows = []
    for block in ENTRY_RE.findall(text):
        if "attribution:" not in block:
            continue
        src = re.search(r'src: "/content-images/([^"]+)"', block).group(1)
        creator = re.search(r'creator: "([^"]+)"', block).group(1)
        url = re.search(r'sourceUrl: "([^"]+)"', block).group(1)
        licence = re.search(r'license: "([^"]+)"', block).group(1)
        licence_url = re.search(r'licenseUrl: "([^"]+)"', block)
        name = urllib.parse.unquote(url.rsplit("File:", 1)[-1]).rsplit(".", 1)[0].replace("_", " ")
        licence_cell = f"[{licence}]({licence_url.group(1)})" if licence_url else licence
        rows.append(f"| `{src}` | {creator} | [{name}]({url}) | {licence_cell} |")

    rows.sort()

    component_rows = []
    component_text = COMPONENT_SOURCE.read_text(encoding="utf-8")
    for block in re.findall(r"= \{(.*?)\n\};", component_text, re.S):
        src = re.search(r'src: "([^"]+)"', block)
        creator = re.search(r'creator: "([^"]+)"', block)
        url = re.search(r'sourceUrl: "([^"]+)"', block)
        licence = re.search(r'license: "([^"]+)"', block)
        if not (src and creator and url and licence):
            continue
        licence_url = re.search(r'licenseUrl: "([^"]+)"', block)
        name = urllib.parse.unquote(url.group(1).rsplit("File:", 1)[-1]).rsplit(".", 1)[0].replace("_", " ")
        cell = f"[{licence.group(1)}]({licence_url.group(1)})" if licence_url else licence.group(1)
        component_rows.append(f"| `{src.group(1)}` | {creator.group(1)} | [{name}]({url.group(1)}) | {cell} |")

    body = HEADER + "\n".join(rows) + "\n"
    if component_rows:
        body += COMPONENT_HEADER + "\n".join(sorted(component_rows)) + "\n"
    TARGET.write_text(body, encoding="utf-8")
    print(f"{len(rows)} unit images + {len(component_rows)} component assets written to {TARGET.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
